module.exports = {
  primary: [
    { name: "HTML" },
    { name: "CSS" },
    { name: "JavaScript" },
    { name: "TypeScript" },
    { name: "Node.js" },
    { name: "Express" },
    { name: "React" },
    { name: "Next.js" },
    { name: "PostgreSQL" },
    { name: "Prisma" },
    { name: "GraphQL" },
    { name: "git" },
  ],
  secondary: [
    { name: "ML & AI" },
    { name: "LLMs" },
    { name: "Python" },
    { name: "ElasticSearch" },
    { name: "GCP" },
    { name: "Snowflake" },
    { name: "TailwindCSS" },
    { name: "MongoDB" },
    { name: "Vue.js" },
    { name: "Eleventy" },
    { name: "AWS EC2" },
    { name: "Django" },
  ],
};
