module.exports = {
  primary: [
    { name: 'HTML' },
    { name: 'CSS' },
    { name: 'JavaScript' },
    { name: 'React' },
    { name: 'Node.js' },
    { name: 'Express' },
    { name: 'MongoDB' },
    { name: 'PostgreSQL' },
    { name: 'Git' },
    { name: 'GitHub' },
  ],
  secondary: [
    { name: 'TypeScript' },
    { name: 'GraphQL' },
    { name: 'Vue.js' },
    { name: 'TailwindCSS' },
    { name: 'Eleventy' },
    { name: 'Heroku' },
    { name: 'AWS EC2' },
    { name: 'GitHub Actions' },
    { name: 'Python' },
    { name: 'Django' },
  ],
};
